modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="adventurecraft"
version="1.0.0"
displayName="AdventureCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Bennett, MCreator"

[[dependencies.adventurecraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



